# Generated by Django 5.0.4 on 2024-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_github_alter_user_linkdin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام کامل'),
        ),
    ]
