# Generated by Django 5.0.4 on 2024-08-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
