# Generated by Django 5.0.4 on 2024-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number_new',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='شماره تلفن جدید'),
        ),
    ]
