# Generated by Django 5.0.4 on 2024-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_phone_number_new_remove_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='عکس پروفایل'),
        ),
    ]
