# Generated by Django 5.0.4 on 2024-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seriesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='seseaons',
            field=models.IntegerField(),
        ),
    ]
