# Generated by Django 5.0.4 on 2024-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_seriesmodel_hours_alter_seriesmodel_seseaons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='discount_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='main_price',
            field=models.CharField(max_length=20),
        ),
    ]
