# Generated by Django 5.0.4 on 2024-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_articleblogmodel_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogmodel',
            name='author_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
