# Generated by Django 5.0.4 on 2024-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articleblogmodel_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
