# Generated by Django 5.0.4 on 2024-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_seriesmodel_built_in_seriesmodel_course_extra_des1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmodel',
            name='author_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
