# Generated by Django 5.0.4 on 2024-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_commentsectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('work_time', models.CharField(max_length=20)),
                ('about_us', models.IntegerField()),
                ('useful_links', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'پیاده سازی فوتر',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
