# Generated by Django 5.0.4 on 2024-07-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_footer_comment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
