# Generated by Django 5.0.4 on 2024-07-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_seriesmodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesmodel',
            name='is_paid',
        ),
    ]
