# Generated by Django 5.0.4 on 2024-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_seriesmodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='discount_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
