# Generated by Django 5.0.4 on 2024-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_seriesmodel_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
