# Generated by Django 5.0.4 on 2024-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_seriesmodel_language_kinds_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesmodel',
            name='language_kinds',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='language_kinds',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
