# Generated by Django 5.0.4 on 2024-07-10 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_seriesmodel_language_kinds_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesmodel',
            name='language_kinds',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='home.category')),
            ],
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='language_kinds',
            field=models.ManyToManyField(blank=True, to='home.category'),
        ),
    ]
