# Generated by Django 5.0.4 on 2024-07-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_seriesmodel_language_kinds_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmodel',
            name='is_perchesed',
            field=models.BooleanField(default=False),
        ),
    ]
