# Generated by Django 5.0.4 on 2024-07-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_seriesmodel_is_perchesed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmodel',
            name='course_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images'),
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='course_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seriesmodel',
            name='course_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
                ('video_url', models.URLField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.seriesmodel')),
            ],
        ),
    ]
