# Generated by Django 5.0.4 on 2024-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_episode_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesmodel',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='seriesmodel',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='seriesmodel',
            name='course_level',
        ),
        migrations.RemoveField(
            model_name='seriesmodel',
            name='course_tags',
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
