# Generated by Django 5.0.4 on 2024-07-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_episode_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='sesson_number',
            field=models.IntegerField(default=1),
        ),
    ]
