# Generated by Django 5.0.4 on 2024-07-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_episode_sesson_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='sesson_number',
            new_name='season_number',
        ),
    ]
