# Generated by Django 5.0.4 on 2024-07-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_sesson_number_episode_season_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='title',
            new_name='course_title',
        ),
        migrations.AddField(
            model_name='episode',
            name='season_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
