# Generated by Django 5.0.4 on 2024-07-27 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_title_episode_course_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='course',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_title',
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='home.seriesmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.season'),
        ),
    ]
