# Generated by Django 5.0.4 on 2024-07-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_course_title_episode_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='course',
        ),
        migrations.RemoveField(
            model_name='season',
            name='number',
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.season'),
        ),
    ]
