# Generated by Django 5.0.4 on 2024-07-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_season_course_remove_season_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.AddField(
            model_name='episode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.seriesmodel'),
        ),
        migrations.AddField(
            model_name='episode',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
