# Generated by Django 5.0.4 on 2024-07-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_episode_season_remove_episode_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='course',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_title',
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='home.seriesmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.season'),
        ),
    ]
