# Generated by Django 5.0.4 on 2024-07-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_course_title_episode_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='course',
            new_name='series',
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
