# Generated by Django 5.0.4 on 2024-07-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_episode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'فصل', 'verbose_name_plural': 'فصل ها'},
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره فصل'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='home.seriesmodel', verbose_name='دوره ها'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان فصل'),
        ),
    ]
