# Generated by Django 5.0.4 on 2024-07-28 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_season_options_alter_season_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='مولف'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='author_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مولف'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='built_in',
            field=models.TextField(blank=True, null=True, verbose_name='ساختار'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='course_extra_des1',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی 1'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='course_extra_des2',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی 2'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='discount_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='قیمت تخفیف'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='free',
            field=models.BooleanField(default=True, verbose_name='رایگان'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='hours',
            field=models.IntegerField(verbose_name='تعداد ساعت'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='image',
            field=models.ImageField(upload_to='series_courses', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='introdution_course',
            field=models.TextField(blank=True, null=True, verbose_name='معرفی دوره'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='is_compeleted',
            field=models.BooleanField(default=True, verbose_name='تکمیل شده'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='language_kinds',
            field=models.CharField(max_length=30, null=True, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='main_price',
            field=models.CharField(max_length=20, verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='seseaons',
            field=models.IntegerField(verbose_name='تعداد فصل'),
        ),
        migrations.AlterField(
            model_name='seriesmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
