# Generated by Django 5.0.4 on 2024-07-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_seriesmodel_language_kinds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriesmodel',
            old_name='category',
            new_name='language_kinds',
        ),
    ]
