# Generated by Django 5.0.4 on 2024-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_seriesmodel_language_kinds_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='language_kinds',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
