# Generated by Django 5.0.4 on 2024-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_category_alter_seriesmodel_language_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='seseaons',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد فصل'),
        ),
    ]
