# Generated by Django 5.0.4 on 2024-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_footer_options_remove_footer_useful_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='اسلاگ دسته بندی را وارد کنید', null=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان دسته بندی را وارد کنید', max_length=100, null=True, verbose_name='عنوان دسته بندی'),
        ),
    ]
