# Generated by Django 5.0.4 on 2024-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_commentreplymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmodel',
            name='main_price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='قیمت اصلی'),
        ),
        migrations.DeleteModel(
            name='CommentReplyModel',
        ),
    ]
