# Generated by Django 5.0.4 on 2024-08-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_seriesmodel_main_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsectionmodel',
            old_name='parent',
            new_name='parent_comment',
        ),
        migrations.AlterField(
            model_name='commentsectionmodel',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seriesmodel'),
        ),
    ]
