# Generated by Django 5.0.4 on 2024-08-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_rename_parent_commentsectionmodel_parent_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsectionmodel',
            old_name='parent_comment',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='commentsectionmodel',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.seriesmodel'),
        ),
    ]
