# Generated by Django 5.0.4 on 2024-08-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
