# Generated by Django 5.0.4 on 2024-08-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='text',
        ),
    ]
