# Generated by Django 5.0.4 on 2024-08-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_rename_content_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_set', to='home.commentsectionmodel'),
        ),
    ]
