# Generated by Django 5.0.4 on 2024-08-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='commentsectionmodel',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'فوتر', 'verbose_name_plural': 'فوتر'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'ریپلای', 'verbose_name_plural': 'ریپلای ها'},
        ),
    ]
