# Generated by Django 5.0.4 on 2024-08-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_counselingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CounselingModel',
        ),
    ]
