# Generated by Django 5.0.4 on 2024-08-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
