# Generated by Django 5.0.4 on 2024-08-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_delete_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counseling',
            options={'verbose_name_plural': 'بدنه'},
        ),
    ]
