# Generated by Django 5.0.4 on 2024-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_counseling_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsectionmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
