# Generated by Django 5.0.4 on 2024-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_commentsectionmodel_is_active_reply_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
