# Generated by Django 5.0.4 on 2024-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_alter_commentsectionmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
