# Generated by Django 5.0.4 on 2024-08-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_alter_episode_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='فایل ویدئو'),
        ),
    ]
