# Generated by Django 5.0.4 on 2024-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
