# Generated by Django 5.0.4 on 2024-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_alter_seriesmodel_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmodel',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
