# Generated by Django 5.0.4 on 2024-08-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
