# Generated by Django 5.0.4 on 2024-08-30 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_alter_articleblogmodel_language_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblogmodel',
            name='language_kinds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogss', to='home.categoryblog'),
        ),
    ]
