# Generated by Django 5.0.4 on 2024-08-30 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_alter_articleblogmodel_language_kinds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.AlterField(
            model_name='articleblogmodel',
            name='language_kinds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='home.category', verbose_name='زبان'),
        ),
        migrations.RemoveField(
            model_name='articleblogmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='seriesmodel',
            name='author_image',
        ),
        migrations.DeleteModel(
            name='CategoryBlog',
        ),
    ]
