# Generated by Django 5.0.4 on 2024-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_delete_advantage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='articles_blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleblogmodel',
            name='language_kinds',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
    ]
