# Generated by Django 5.0.4 on 2024-08-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_alter_articleblogmodel_language_kinds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblogmodel',
            name='language_kinds',
            field=models.CharField(max_length=30),
        ),
    ]
