# Generated by Django 5.0.4 on 2024-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_alter_articleblogmodel_language_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblogmodel',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
