# Generated by Django 5.0.4 on 2024-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_title'),
        ('home', '0012_footer_comment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='series',
            field=models.ManyToManyField(related_name='orders', to='home.seriesmodel'),
        ),
    ]
