# Generated by Django 5.0.4 on 2024-07-08 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_order_series'),
        ('home', '0014_remove_seriesmodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='home.seriesmodel'),
        ),
    ]
