# Generated by Django 5.0.4 on 2024-07-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='series',
        ),
    ]
