# Generated by Django 5.0.4 on 2024-07-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='series',
        ),
    ]
