# Generated by Django 5.0.4 on 2024-07-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_order_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='series',
        ),
    ]
