# Generated by Django 5.0.4 on 2024-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='percentage',
            field=models.SmallIntegerField(default=0, verbose_name='درصد'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
